import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Three from './components/tri_angles_shapes.jsx';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Fingerprint Detection",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* glass effect */}
        <div className="absolute inset-0 -z-10 backdrop-blur-md /30"></div>
        <div className="background -z-20 fixed top-0 left-0 w-full h-full">
          <Three></Three>
        </div>
        {children}
      </body>
    </html>
  );
}
